/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WycenaRouteImport } from './routes/wycena'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as OFirmieRouteImport } from './routes/o-firmie'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktyIndexRouteImport } from './routes/produkty.index'
import { Route as ProduktyProdukcjaNaZamowienieRouteImport } from './routes/produkty.produkcja-na-zamowienie'
import { Route as ProduktyOsprzetRouteImport } from './routes/produkty.osprzet'
import { Route as ProduktyKonstrukcjeStaloweRouteImport } from './routes/produkty.konstrukcje-stalowe'
import { Route as ProduktyBalastyRouteImport } from './routes/produkty.balasty'
import { Route as ProduktyBalastyIndexRouteImport } from './routes/produkty.balasty.index'
import { Route as ProduktyBalastyTypeRouteImport } from './routes/produkty.balasty.$type'
import { Route as ProduktyBalastyTypeIndexRouteImport } from './routes/produkty.balasty.$type.index'
import { Route as ProduktyBalastyTypeWeightRouteImport } from './routes/produkty.balasty.$type.$weight'

const WycenaRoute = WycenaRouteImport.update({
  id: '/wycena',
  path: '/wycena',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const OFirmieRoute = OFirmieRouteImport.update({
  id: '/o-firmie',
  path: '/o-firmie',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyIndexRoute = ProduktyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduktyRoute,
} as any)
const ProduktyProdukcjaNaZamowienieRoute =
  ProduktyProdukcjaNaZamowienieRouteImport.update({
    id: '/produkcja-na-zamowienie',
    path: '/produkcja-na-zamowienie',
    getParentRoute: () => ProduktyRoute,
  } as any)
const ProduktyOsprzetRoute = ProduktyOsprzetRouteImport.update({
  id: '/osprzet',
  path: '/osprzet',
  getParentRoute: () => ProduktyRoute,
} as any)
const ProduktyKonstrukcjeStaloweRoute =
  ProduktyKonstrukcjeStaloweRouteImport.update({
    id: '/konstrukcje-stalowe',
    path: '/konstrukcje-stalowe',
    getParentRoute: () => ProduktyRoute,
  } as any)
const ProduktyBalastyRoute = ProduktyBalastyRouteImport.update({
  id: '/balasty',
  path: '/balasty',
  getParentRoute: () => ProduktyRoute,
} as any)
const ProduktyBalastyIndexRoute = ProduktyBalastyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduktyBalastyRoute,
} as any)
const ProduktyBalastyTypeRoute = ProduktyBalastyTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ProduktyBalastyRoute,
} as any)
const ProduktyBalastyTypeIndexRoute =
  ProduktyBalastyTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProduktyBalastyTypeRoute,
  } as any)
const ProduktyBalastyTypeWeightRoute =
  ProduktyBalastyTypeWeightRouteImport.update({
    id: '/$weight',
    path: '/$weight',
    getParentRoute: () => ProduktyBalastyTypeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/produkty': typeof ProduktyRouteWithChildren
  '/wycena': typeof WycenaRoute
  '/produkty/balasty': typeof ProduktyBalastyRouteWithChildren
  '/produkty/konstrukcje-stalowe': typeof ProduktyKonstrukcjeStaloweRoute
  '/produkty/osprzet': typeof ProduktyOsprzetRoute
  '/produkty/produkcja-na-zamowienie': typeof ProduktyProdukcjaNaZamowienieRoute
  '/produkty/': typeof ProduktyIndexRoute
  '/produkty/balasty/$type': typeof ProduktyBalastyTypeRouteWithChildren
  '/produkty/balasty/': typeof ProduktyBalastyIndexRoute
  '/produkty/balasty/$type/$weight': typeof ProduktyBalastyTypeWeightRoute
  '/produkty/balasty/$type/': typeof ProduktyBalastyTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/wycena': typeof WycenaRoute
  '/produkty/konstrukcje-stalowe': typeof ProduktyKonstrukcjeStaloweRoute
  '/produkty/osprzet': typeof ProduktyOsprzetRoute
  '/produkty/produkcja-na-zamowienie': typeof ProduktyProdukcjaNaZamowienieRoute
  '/produkty': typeof ProduktyIndexRoute
  '/produkty/balasty': typeof ProduktyBalastyIndexRoute
  '/produkty/balasty/$type/$weight': typeof ProduktyBalastyTypeWeightRoute
  '/produkty/balasty/$type': typeof ProduktyBalastyTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/produkty': typeof ProduktyRouteWithChildren
  '/wycena': typeof WycenaRoute
  '/produkty/balasty': typeof ProduktyBalastyRouteWithChildren
  '/produkty/konstrukcje-stalowe': typeof ProduktyKonstrukcjeStaloweRoute
  '/produkty/osprzet': typeof ProduktyOsprzetRoute
  '/produkty/produkcja-na-zamowienie': typeof ProduktyProdukcjaNaZamowienieRoute
  '/produkty/': typeof ProduktyIndexRoute
  '/produkty/balasty/$type': typeof ProduktyBalastyTypeRouteWithChildren
  '/produkty/balasty/': typeof ProduktyBalastyIndexRoute
  '/produkty/balasty/$type/$weight': typeof ProduktyBalastyTypeWeightRoute
  '/produkty/balasty/$type/': typeof ProduktyBalastyTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-firmie'
    | '/produkty'
    | '/wycena'
    | '/produkty/balasty'
    | '/produkty/konstrukcje-stalowe'
    | '/produkty/osprzet'
    | '/produkty/produkcja-na-zamowienie'
    | '/produkty/'
    | '/produkty/balasty/$type'
    | '/produkty/balasty/'
    | '/produkty/balasty/$type/$weight'
    | '/produkty/balasty/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-firmie'
    | '/wycena'
    | '/produkty/konstrukcje-stalowe'
    | '/produkty/osprzet'
    | '/produkty/produkcja-na-zamowienie'
    | '/produkty'
    | '/produkty/balasty'
    | '/produkty/balasty/$type/$weight'
    | '/produkty/balasty/$type'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-firmie'
    | '/produkty'
    | '/wycena'
    | '/produkty/balasty'
    | '/produkty/konstrukcje-stalowe'
    | '/produkty/osprzet'
    | '/produkty/produkcja-na-zamowienie'
    | '/produkty/'
    | '/produkty/balasty/$type'
    | '/produkty/balasty/'
    | '/produkty/balasty/$type/$weight'
    | '/produkty/balasty/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  OFirmieRoute: typeof OFirmieRoute
  ProduktyRoute: typeof ProduktyRouteWithChildren
  WycenaRoute: typeof WycenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wycena': {
      id: '/wycena'
      path: '/wycena'
      fullPath: '/wycena'
      preLoaderRoute: typeof WycenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-firmie': {
      id: '/o-firmie'
      path: '/o-firmie'
      fullPath: '/o-firmie'
      preLoaderRoute: typeof OFirmieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty/': {
      id: '/produkty/'
      path: '/'
      fullPath: '/produkty/'
      preLoaderRoute: typeof ProduktyIndexRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/produkty/produkcja-na-zamowienie': {
      id: '/produkty/produkcja-na-zamowienie'
      path: '/produkcja-na-zamowienie'
      fullPath: '/produkty/produkcja-na-zamowienie'
      preLoaderRoute: typeof ProduktyProdukcjaNaZamowienieRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/produkty/osprzet': {
      id: '/produkty/osprzet'
      path: '/osprzet'
      fullPath: '/produkty/osprzet'
      preLoaderRoute: typeof ProduktyOsprzetRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/produkty/konstrukcje-stalowe': {
      id: '/produkty/konstrukcje-stalowe'
      path: '/konstrukcje-stalowe'
      fullPath: '/produkty/konstrukcje-stalowe'
      preLoaderRoute: typeof ProduktyKonstrukcjeStaloweRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/produkty/balasty': {
      id: '/produkty/balasty'
      path: '/balasty'
      fullPath: '/produkty/balasty'
      preLoaderRoute: typeof ProduktyBalastyRouteImport
      parentRoute: typeof ProduktyRoute
    }
    '/produkty/balasty/': {
      id: '/produkty/balasty/'
      path: '/'
      fullPath: '/produkty/balasty/'
      preLoaderRoute: typeof ProduktyBalastyIndexRouteImport
      parentRoute: typeof ProduktyBalastyRoute
    }
    '/produkty/balasty/$type': {
      id: '/produkty/balasty/$type'
      path: '/$type'
      fullPath: '/produkty/balasty/$type'
      preLoaderRoute: typeof ProduktyBalastyTypeRouteImport
      parentRoute: typeof ProduktyBalastyRoute
    }
    '/produkty/balasty/$type/': {
      id: '/produkty/balasty/$type/'
      path: '/'
      fullPath: '/produkty/balasty/$type/'
      preLoaderRoute: typeof ProduktyBalastyTypeIndexRouteImport
      parentRoute: typeof ProduktyBalastyTypeRoute
    }
    '/produkty/balasty/$type/$weight': {
      id: '/produkty/balasty/$type/$weight'
      path: '/$weight'
      fullPath: '/produkty/balasty/$type/$weight'
      preLoaderRoute: typeof ProduktyBalastyTypeWeightRouteImport
      parentRoute: typeof ProduktyBalastyTypeRoute
    }
  }
}

interface ProduktyBalastyTypeRouteChildren {
  ProduktyBalastyTypeWeightRoute: typeof ProduktyBalastyTypeWeightRoute
  ProduktyBalastyTypeIndexRoute: typeof ProduktyBalastyTypeIndexRoute
}

const ProduktyBalastyTypeRouteChildren: ProduktyBalastyTypeRouteChildren = {
  ProduktyBalastyTypeWeightRoute: ProduktyBalastyTypeWeightRoute,
  ProduktyBalastyTypeIndexRoute: ProduktyBalastyTypeIndexRoute,
}

const ProduktyBalastyTypeRouteWithChildren =
  ProduktyBalastyTypeRoute._addFileChildren(ProduktyBalastyTypeRouteChildren)

interface ProduktyBalastyRouteChildren {
  ProduktyBalastyTypeRoute: typeof ProduktyBalastyTypeRouteWithChildren
  ProduktyBalastyIndexRoute: typeof ProduktyBalastyIndexRoute
}

const ProduktyBalastyRouteChildren: ProduktyBalastyRouteChildren = {
  ProduktyBalastyTypeRoute: ProduktyBalastyTypeRouteWithChildren,
  ProduktyBalastyIndexRoute: ProduktyBalastyIndexRoute,
}

const ProduktyBalastyRouteWithChildren = ProduktyBalastyRoute._addFileChildren(
  ProduktyBalastyRouteChildren,
)

interface ProduktyRouteChildren {
  ProduktyBalastyRoute: typeof ProduktyBalastyRouteWithChildren
  ProduktyKonstrukcjeStaloweRoute: typeof ProduktyKonstrukcjeStaloweRoute
  ProduktyOsprzetRoute: typeof ProduktyOsprzetRoute
  ProduktyProdukcjaNaZamowienieRoute: typeof ProduktyProdukcjaNaZamowienieRoute
  ProduktyIndexRoute: typeof ProduktyIndexRoute
}

const ProduktyRouteChildren: ProduktyRouteChildren = {
  ProduktyBalastyRoute: ProduktyBalastyRouteWithChildren,
  ProduktyKonstrukcjeStaloweRoute: ProduktyKonstrukcjeStaloweRoute,
  ProduktyOsprzetRoute: ProduktyOsprzetRoute,
  ProduktyProdukcjaNaZamowienieRoute: ProduktyProdukcjaNaZamowienieRoute,
  ProduktyIndexRoute: ProduktyIndexRoute,
}

const ProduktyRouteWithChildren = ProduktyRoute._addFileChildren(
  ProduktyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  OFirmieRoute: OFirmieRoute,
  ProduktyRoute: ProduktyRouteWithChildren,
  WycenaRoute: WycenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
